### PR TITLE
Added session creation timestamp

### PR DESCRIPTION
**Pull request by danielvogel**

### CODE REVIEW

**Comment by commana** [comment]
I guess this change was part of the session import/export feature? I pushed it in a topic branch like I did in arsnova-mobile. @dgerhardt and I will keep you updated on our progress towards a new release.

**Comment by danielvogel** [comment]
No, this change added the creation time to sessions.

**Comment by commana** [comment]
Pushed the new changes. However, I dislike the use of the underscore in the URL. We've been using lowercase for all URLs, so I would appreciate it if you could change the URL accordingly.

**Comment by danielvogel** [comment]
Ok, we'll change that before the final public pool draft.

**Comment by dgerhardt** [comment]
Merged.

**Pull request closed without merging**
